### ISSUE TITLE
run_scenicplus error

### ISSUE THREAD

**Issue by poddan01** [aertslab/scenicplus#270] opened 2023-12-14 19:45 UTC
Hi! Thank you for such a great tool. I am getting an error in the run_scenicplus step. Here is the code I am using : 
run_scenicplus(
        scplus_obj = scplus_obj,
        variable = ['annotation'],
        species = 'hsapiens',
        assembly = 'hg38',
        tf_file = '/data/TF_names_v_1.01.txt',
        save_path = os.path.join(outDir, 'output3'),
        biomart_host = biomart_host,
        upstream = [1000, 150000],
        downstream = [1000, 150000],
        calculate_TF_eGRN_correlation = True,
        calculate_DEGs_DARs = True,
        export_to_loom_file = True,
        export_to_UCSC_file = True,
        n_cpu = 10,
        _temp_dir = os.path.join(tmpDir, 'ray_spill'))

Here is the error : 
<img width="867" alt="scenicplus_error" src="https://github.com/aertslab/scenicplus/assets/153862350/afee2762-c6a4-45ac-a3b9-cfcb0f6387e8">

Could you please help me with this? Thanks.

**Comment by SeppeDeWinter** [comment] 2023-12-15 10:05
Hi @poddan01 

This is the same issue as this one: https://github.com/aertslab/scenicplus/issues/203. 
I was not able to reproduce this issue, it is related though to the UMAP and Numba versions you are using.


The good news is that once you reach this step, the complete SCENIC+ analysis has already finished (you just don't have a UMAP of the eRegulon enrichment scores).

So make sure to save your SCENIC+ object, this you can still use for all downstream analysis (except plotting UMAPS).

(closing this issue here, but feel free to comment on https://github.com/aertslab/scenicplus/issues/203).

All the best,

Seppe

**Closed by SeppeDeWinter** 2023-12-15 10:05 UTC
